//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6_FUNDACIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fundacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fundacion()
        {
            this.FundacionCategoria = new HashSet<FundacionCategoria>();
            this.GaleriaImagenes = new HashSet<GaleriaImagenes>();
            this.Ressenya = new HashSet<Ressenya>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono_Contacto { get; set; }
        public string Email_Contacto { get; set; }
        public string Link_Web { get; set; }
        public string HorarioVisita { get; set; }
        public string FotoWeb { get; set; }
        public string FotoRecinto { get; set; }
        public Nullable<int> IDContinent { get; set; }
        public Nullable<int> IDPais { get; set; }
        public Nullable<int> IDCiutat { get; set; }
        public string link_GoogleMaps { get; set; }
    
        public virtual Ciutat Ciutat { get; set; }
        public virtual Continente Continente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundacionCategoria> FundacionCategoria { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GaleriaImagenes> GaleriaImagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ressenya> Ressenya { get; set; }
    }
}
