//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6_FUNDACIO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FundacionesDBEntities : DbContext
    {
        public FundacionesDBEntities()
            : base("name=FundacionesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Ciutat> Ciutat { get; set; }
        public virtual DbSet<Continente> Continente { get; set; }
        public virtual DbSet<Fundacion> Fundacion { get; set; }
        public virtual DbSet<FundacionCategoria> FundacionCategoria { get; set; }
        public virtual DbSet<GaleriaImagenes> GaleriaImagenes { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Ressenya> Ressenya { get; set; }
    }
}
