//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6_FUNDACIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ressenya
    {
        public int ID_Ressenya { get; set; }
        public int ID_Fundacion { get; set; }
        public int Valoracio { get; set; }
        public string Descripcio { get; set; }
    
        public virtual Fundacion Fundacion { get; set; }
    }
}
